import type { Metadata } from "next";
import "./globals.css";
import { googleSans } from "@/libs/Fonts";
import Background from "@/Components/Background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${googleSans.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Background />
        {children}
      </body>
    </html>
  );
}
